services:
  mkdocs:
      build:

        context: .

        dockerfile: ./Dockerfile

      container_name: mydocs

      ports:
          - "8080:80"

      networks:
          - mkdocs-network

     # volumes:
      #    - ./site:/usr/share/nginx/html
networks:
  mkdocs-network:
    driver: bridge
