on:
  push:
  branches:
  - master
jobs:
  build:
    runs-on: ubuntu-22.04
    permission:
      packages: write

    steps:
    #checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to container registory
      uses: docker/login-action@v2
      with:
        registory: gchr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKENN }}

    - name: Build project
      uses: docker/build-push-action@v4
      with:
        tag:
          ghcr.io/${{ github.repositrory }}:latest
          ghcr.io/${{ github.repository }}:${{ github.run_number }}

